-- Migration: Fase 2.2 — Schema updates for raw ingest & simplified auth
-- Changes:
--   - Add provider_seluler, nama_pemilik, perlu_review columns
--   - Make device_id nullable (no longer required)
--   - Make nominal nullable (parser can fail to extract)
--   - Drop unique constraint on (provider, id_transaksi_provider) since
--     id_transaksi_provider is now generated by parser, not client

-- Add new columns
ALTER TABLE public.transaksi
  ADD COLUMN IF NOT EXISTS provider_seluler TEXT,
  ADD COLUMN IF NOT EXISTS nama_pemilik TEXT,
  ADD COLUMN IF NOT EXISTS perlu_review BOOLEAN NOT NULL DEFAULT false;

-- Make device_id nullable (client no longer sends it)
ALTER TABLE public.transaksi ALTER COLUMN device_id DROP NOT NULL;

-- Make nominal nullable (parser may fail to extract)
ALTER TABLE public.transaksi ALTER COLUMN nominal DROP NOT NULL;

-- Drop old unique constraint: id_transaksi_provider is now backend-generated,
-- not client-provided, so the old dedup key no longer makes sense.
-- New dedup strategy: backend can use (provider, raw_notification_text hash) or
-- simply allow duplicates (parser always produces same result for same input).
ALTER TABLE public.transaksi DROP CONSTRAINT IF EXISTS transaksi_provider_unique;

-- Recreate index without the dropped constraint column
DROP INDEX IF EXISTS idx_transaksi_device_id;

-- Add index on perlu_review for dashboard filtering
CREATE INDEX IF NOT EXISTS idx_transaksi_perlu_review ON public.transaksi (perlu_review);